# Experimental!
~ "git: github.com/amatgil/steal-gift" ~ AoCGet

IsSafe ← /×∊⇡₁3×±⊸⊢⧈-
Do!    ← ⧻⊚⊜(^0⊜⋕⊸≠@ )⊸≠@\n

A ← Do!IsSafe
B ← Do!(/∨≡IsSafe⧅₋₁<)

&p$"A: _\nB: _" ⊃A B AoCGet 2024 2

┌─╴test
  ⍤⤙≍ 2 A $ 7 6 4 2 1
          $ 1 2 7 8 9
          $ 9 7 6 2 1
          $ 1 3 2 4 5
          $ 8 6 4 4 1
          $ 1 3 6 7 9

  ⍤⤙≍ 4 B $ 7 6 4 2 1
          $ 1 2 7 8 9
          $ 9 7 6 2 1
          $ 1 3 2 4 5
          $ 8 6 4 4 1
          $ 1 3 6 7 9
└─╴
