# Experimental!
~ "git: github.com/amatgil/steal-gift" ~ AoCGet

Input ← AoCGet 2024 3

A ← /+⊜⍣(×∩°↧₉₉₉⊓∩⋕◌°$"mul(_,_)_")0\+⊸⌕"mul("
B ← /+≡◇(𝄐A⍣°$"_don't()_"∘)°/$"_do()_"

&p$"A: _\nB: _" ⊃A B AoCGet 2024 3

┌─╴test
  ⍤⤙≍ 2024 A $ mul(44,46)
  ⍤⤙≍ 161 A $ xmul(2,4)%&mul[3,7]!@^do_not_mul(5,5)+mul(32,64]then(mul(11,8)mul(8,5))

  ⍤⤙≍48 B $ xmul(2,4)&mul[3,7]!^don't()_mul(5,5)+mul(32,64](mul(11,8)undo()?mul(8,5))
└─╴
