# Experimental!
~ "git: github.com/amatgil/steal-gift" ~ AoCGet

Input       ← AoCGet 2024 19
ParsedInput ← °⊓/$"_, _"/$"_\n_" °$"_\n\n_"Input

A ← /+≡⌞◇(/↧/↥≡⌟◇⦷)
A ← ⧻⊚≡⌞(∊:□""⍥(◴/⊂˜⊞⍚memo⍣⌝⊂◌)∞:▽≡/↥◡≡⌟◇⌕)
B ← 0

$ r, wr, b, g, bwu, rb, gb, br
$ 
$ brwrr
$ bggr
$ gbbr
$ rrbgbr
$ ubwu
$ bwurrg
$ brgr
$ bbrgwb

°⊓/$"_, _"/$"_\n_" °$"_\n\n_"

:

⍚⌟(path(≡□⍚⌞˜⍣⌝⊂◌°□|◇≍""°□))

# ⧻⊚≡⌞(∊:□""⍥(◴/⊂˜⊞⍚memo⍣⌝⊂◌)∞:▽≡/↥◡≡⌟◇⌕)

# &p$"A: _\nB: _" ⊃A B ParsedInput
