# Experimental!
~ "git: github.com/amatgil/steal-gift" ~ AoCGet

Shift ← ≠⟜⬚0↻₋₁₁ ≠⟜⬚0↻₅ ≠⟜⬚0↻₋₆

A ← /+⍜⋯₂₄⍜⍉⍥₂₀₀₀Shift ⊜⋕⊸≠@\n
B ← /↥⊕/+⊛∩/◇⊂⍚(
  ∩⌞▽⊸◰⧈⊟₄⊃⧈-↘₄
)⧋⊢⊥₁₀⍜⋯₂₄⍜⍉⍥₂₀₀₀⊸Shift ⊜⋕⊸≠@\n # This is wrong by 5 for the real example and i do not know why

&p$"A: _\nB: _" ⊃A B AoCGet 2024 22

┌─╴test
  ⍤⤙≍ 37327623 A$ 1
                $ 10
                $ 100
                $ 2024

  ⍤⤙≍ 23 B $ 1
           $ 2
           $ 3
           $ 2024
└─╴
